apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ecc.ui.fullname" . }}
  labels:
    {{- include "ecc.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.ui.autoscaling.enabled }}
  replicas: {{ .Values.ui.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ecc.selectorLabels" (dict "root" . "component" "ui") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ecc.labels" . | nindent 8 }}
        app.kubernetes.io/component: ui
        {{- with .Values.ui.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.ui.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "ecc.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "ecc.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: ui
          image: {{ include "ecc.image" (dict "root" . "image" .Values.ui.image) | quote }}
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.ui.containerPort }}
              protocol: TCP
          env:
            - name: CONVERTER_BACKEND_URL
              value: {{ include "ecc.backendUrl" . | quote }}
            {{- with .Values.ui.resolver }}
            - name: CONVERTER_RESOLVER
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.ui.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.ui.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ui.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
